# Generated by Django 5.2.7 on 2025-11-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField()),
                ('suffix', models.IntegerField()),
                ('url', models.CharField()),
                ('repo', models.CharField()),
                ('repo_id', models.CharField()),
                ('description', models.CharField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
