# Generated by Django 5.2.7 on 2025-11-11 19:00

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_handle_options_handle_created_handle_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jwttoken',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='jwttoken',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jwttoken',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
