# Generated by Django 5.2.7 on 2025-11-13 13:46

import umd_handle.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_jwttoken_options_jwttoken_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handle',
            name='prefix',
            field=models.CharField(choices=[('1903.1', '1903.1')], validators=[umd_handle.api.models.validate_prefix]),
        ),
    ]
