# Generated by Django 5.2.7 on 2025-11-13 13:53

import umd_handle.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_handle_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handle',
            name='repo',
            field=models.CharField(choices=[('aspace', 'aspace'), ('avalon', 'avalon'), ('fcrepo', 'fcrepo'), ('fedora2', 'fedora2')], validators=[umd_handle.api.models.validate_repo]),
        ),
    ]
