# Generated by Django 5.2.7 on 2025-11-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_handle_repo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handle',
            options={},
        ),
        migrations.AddConstraint(
            model_name='handle',
            constraint=models.UniqueConstraint(fields=('prefix', 'suffix'), name='unique_handle_prefix_suffix'),
        ),
    ]
