# Generated by Django 5.2.7 on 2025-11-13 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_handle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handle',
            name='url',
            field=models.CharField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
